### ISSUE TITLE
.regexp control operator support?

### ISSUE THREAD

**Issue by adzialocha** [ericseppanen/cddl-cat#1]
Hi @ericseppanen! Thank you so much for this helpful implementation of `cddl-cat`! We're currently looking into integrating it in https://github.com/p2panda/p2panda

One thing we would need is support for the `.regexp` control operator. Do you have any pointers in what might be required to integrate it into `cddl-cat`?

Thank you!

**Comment by ericseppanen** [comment]
Thanks for opening the issue!

I haven't looked at the details of `.regexp` yet, but I can review the spec and let you know what I think might be involved.

**Comment by adzialocha** [comment]
> I haven't looked at the details of .regexp yet, but I can review the spec and let you know what I think might be involved.

Super, thank you! I'm happy to contribute a PR with some guidance.

**Comment by ericseppanen** [comment]
@adzialocha, could you try the version from the "regexp" branch (PR #2) and let me know if that works for you?

Also, if you have any interesting regular expressions that would be useful as unit tests, feel free to paste them here.

**Comment by adzialocha** [comment]
> @adzialocha, could you try the version from the "regexp" branch (PR https://github.com/ericseppanen/cddl-cat/pull/2) and let me know if that works for you?

Wow, thank you so much! This went really quick! Just tried the branch in our codebase and it works perfectly fine, even in WebAssembly contexts: https://github.com/p2panda/p2panda/pull/248/commits/4e4b20ac6c9bd626a48c8b7fcc043a1c3a3c0a0c

> Also, if you have any interesting regular expressions that would be useful as unit tests, feel free to paste them here.

Our current regular expression is fairly simple: `tstr .regexp "[0-9a-f]{68}"`, I think you already have similar cases covered in the unit tests :+1:

**Comment by ericseppanen** [comment]
I published v. 0.6.0. Let me know if you have any other ideas for improvements!

**Comment by adzialocha** [comment]
> Let me know if you have any other ideas for improvements!

Thank you, I'll add some issues if there is any ideas.
